language: csharp
solution: RestWell.sln
dist: trusty
mono: none
dotnet: 2.0.0
install:
  - dotnet restore
script:
  - dotnet test TestWell.Test.Component/TestWell.Test.Component.csproj
notifications:
  email: false
